### ISSUE TITLE
snpm-exporter error

### ISSUE THREAD

**Issue by UncleVic** [ddiiwoong/synology-prometheus#13]
Hi there,

The snpm-exporter container can't parse config with 2 errors
```
Possible old config file, see https://github.com/prometheus/snmp_exporter/blob/main/auth-split-migration.md
Error parsing config file" err="yaml: unmarshal errors:\n  line 2: field synology not found in type config.Config
```
I tryed using `snmp-0.24.x.yml` but with it I can't see any data in the dashboard.

**Comment by UncleVic** [comment]
Exactly, it works with `snmp-0.24.x.yml` but I cant see Synology metrics. Ex. `systemStatus` and others :(

**Comment by UncleVic** [comment]
I managed to fix it!
I think, it depended on the exporter version... I'm not sure but I changed `snmp.yml` like that
```yaml
auths:
  public_v1:
    community: public
    security_level: noAuthNoPriv
    auth_protocol: MD5
    priv_protocol: DES
    version: 1
  public_v2:
    community: public
    security_level: noAuthNoPriv
    auth_protocol: MD5
    priv_protocol: DES
    version: 2
modules:
  synology: # tab need here and below
...
# you can remove it
#  auth:
#    community: synology
```

And I changed `community` to `public` in the syno settings of course
